---
name: 'Docker Image CI'

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build-test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Build the Docker image'
        run: "docker build . --file Dockerfile --tag nmap:${GITHUB_RUN_ID}"
      - uses: 'e1himself/goss-installation-action'
      - name: 'Test the Docker image'
        run: |
          export GOSS_FILES_STRATEGY=cp
          export GOSS_SLEEP=5
          dgoss run -it --entrypoint bash nmap:${GITHUB_RUN_ID}
